### ISSUE TITLE
Questions about the plugins features

### ISSUE THREAD

**Issue by sharpedavid** [gbbirkisson/kong-plugin-jwt-keycloak#24]
Hi @gbbirkisson, thanks for your contribution to open source! I'm in the early stages of evaluating Kong's capabilities, and your plugin shows up high in Google searches for integrating Kong with Keycloak. I have a few questions about your plugin. If you have time to answer them great, but if not, no worries and feel free to close this.

From the README.md, you say that one of the main benefits of the plugin are "Rotating public keys". I see that the [official JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt) does signature validation, but you must manually upload the public key. Your plugin automatically downloads and caches the certificates from Keycloak, right? 

Another benefit you list is "Matching Keycloak users/clients to Kong consumers". I'm having trouble understanding what the use case for this is, in large part because I'm new to Kong. Reading your source code, you have a function called `set_consumer(consumer, credential, token)`, so I thought maybe this matching feature was to provide an additional layer of authentication, but you only ever call `set_consumer(consumer, nil, nil)`. What's the use case?

My last question: is there anything in this plugin that really makes it Keycloak-specific, or could it be used with any spec-compliant OIDC server?

BONUS QUESTION: You use Makefiles nicely. Are they your creation? Is that common practice in Kong or Lua?

**Comment by gbbirkisson** [comment]
Hi, thanks for you interest. Here are answers to you questions:

> ... but you must manually upload the public key. Your plugin automatically downloads and caches the certificates from Keycloak, right? ...

This plugin also does signature validation, it downloads the public keys automatically from keycloak. Inside each token, there is an `iss` field that Keycloak set to `https://my.keycloak.server/realm/myrealm`. Then the plugin applies the `well_known_template` configuration to get the well known endpoint: `https://my.keycloak.server/realm/myrealm/.well-known/openid-configuration`. From there it fetches the available keys, caches them and uses them to validate the signatures.

> ... Matching Keycloak users/clients to Kong consumers ...

Some other plugins in Kong work on consumers. That is an entity that is managed by Kong. This plugin could just let the request through on valid tokens, but it also supports matching some token claim (by default `azp`) to a consumer in kong. Meaning that you can use other plugins requiring consumers in conjunction with this one.

> ... anything in this plugin that really makes it Keycloak-specific ...

In theory, no. And it could be generalized for all OIDC providers. The public key and signature validation is generic and could be used on any OIDC server. But as it is now, it assumes the claim structure that keycloak creates and also that the `iss` field is set to a public url pointing to a realm. So for now it is keycloak specific. For a more generic plugin, you can consider [Nokia's OIDC plugin](https://github.com/nokia/kong-oidc).

> ... Makefiles ...

Thanks for the complement. No I don't think this is common practice, yes I did create them myself. I wanted to create extensive tests and use docker to do it, so that was the first thing that came to my mind. This is probably my most ambitious makefile endeavour to date.

**Comment by sharpedavid** [comment]
I appreciate you taking the time to respond, @gbbirkisson. That all makes sense.

I have been looking at the Nokia plugin, but for my purposes there are some drawbacks (this part is just FYI in case you're interested):

* Your plugin has arguably better documentation. 
* We're using Keycloak.
* The Nokia plugin hasn't been updated in a long time. It does seem abandoned. I know you could leave whenever you feel like it too, but in the meantime it makes a difference.
* The Nokia plugin implements the authorization code flow to retrieve an access token, but we don't need this. It does offer a "bearer only" mode, but I like the idea of a smaller plugin, again especially when the maintainers can disappear whenever.
* The Nokia plugin appears to use Keycloak's token introspection endpoint for all token validation. Some people will want this, but it adds load and latency. Your approach of downloading and caching the public keys for signature validation is better for us.
